apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddyjavaapp-deploy
  labels:
    app: reddyjavaapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddyjavaapp
  template:
    metadata:
      labels:
        app: reddyjavaapp
    spec:
      containers:
      - name: reddyjavaapp-container
        image: maha4iac/myjavaaplication:2
        ports:
        - containerPort: 8080