apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 5
  selector:
    app: myjavaapp
    version: 2.7.1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.7.1
    spec:
      containers:
      - name:  my-java-container
        image: maha4iac/mymahaapp:1
        ports:
        - containerPort: 8080